### ISSUE TITLE
Некоректен пример за задача 7

### ISSUE THREAD

**Issue by sttodorov** [FMIjs/js-lectures-2015#5]
Напишете функция setBits(m, n, i, j), която приема като аргументи числата m, n, i, j. Функцията задава битовете на m в диапазона i, j със стойност n, т.е.:

Вход:
m = 10000010
n =      11010
i = 2
j = 5
Резултат:
10110110

В така дадения пример не всички битове на m от i до j са променени. Втория бит трябва да е 0.
Диапазона на битове от 2ри до 5ти - 100(0001)0. В  примера е променен и шестия бит.
Ако съм разбрал условето правилно, резултата (r) трябва да бъде:
m = 10000010
## n =    (1)1010

r =   10010100

**Comment by mgechev** [comment]
```
                     i     j
bit index   -> 0 1 | 2 3 4 5 | 6 7
m           -> 1 0 | 0 0 0 0 | 1 0
n           ->     | 1 1 0 1 | 0
setBits(..) -> 1 0 | 1 1 0 1 | 1 0
```
